create table if not exists shops(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,logo_url text,color text not null default '#be123c',whatsapp text,owner_id uuid,plan text not null default 'basic',monthly_fee numeric not null default 0,status text not null default 'trial' check (status in ('trial','active','suspended')),paid_until date,created_at timestamptz default now());
create table if not exists platform_admins(user_id uuid primary key);
insert into platform_admins select user_id from owners on conflict do nothing;
insert into shops(slug,name,logo_url,color,whatsapp,owner_id,status) select 'main',name,logo_url,color,whatsapp,(select user_id from owners limit 1),'active' from shop_settings on conflict do nothing;
alter table items add column if not exists shop_id uuid references shops(id);
alter table orders add column if not exists shop_id uuid references shops(id);
update items set shop_id=(select id from shops where slug='main') where shop_id is null;
update orders set shop_id=(select id from shops where slug='main') where shop_id is null;
alter table shops enable row level security;
create or replace function is_platform() returns boolean language sql security definer stable as $$ select exists(select 1 from platform_admins where user_id=auth.uid()) $$;
create or replace function owns(s uuid) returns boolean language sql security definer stable as $$ select is_platform() or exists(select 1 from shops where id=s and owner_id=auth.uid()) $$;
drop policy if exists "owner items" on items; drop policy if exists "owner orders" on orders; drop policy if exists "owner write" on storage.objects;
create policy "owner items" on items for all using (owns(shop_id)) with check (owns(shop_id));
create policy "owner orders" on orders for all using (owns(shop_id)) with check (owns(shop_id));
create policy "owner write" on storage.objects for all using (bucket_id='items' and (is_platform() or exists(select 1 from shops where owner_id=auth.uid()))) with check (bucket_id='items' and (is_platform() or exists(select 1 from shops where owner_id=auth.uid())));
create policy "read shops" on shops for select using (true);
create policy "owner edits shop" on shops for update using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "platform shops" on shops for all using (is_platform()) with check (is_platform());
create policy "self admin" on platform_admins for select using (user_id=auth.uid());
create or replace function guard_shop() returns trigger language plpgsql as $$ begin if not is_platform() and (new.plan,new.monthly_fee,new.status,new.paid_until,new.owner_id,new.slug) is distinct from (old.plan,old.monthly_fee,old.status,old.paid_until,old.owner_id,old.slug) then raise exception 'not allowed'; end if; return new; end $$;
create trigger guard_shop before update on shops for each row execute function guard_shop();
drop function if exists place_order(text,text,text,text,jsonb,numeric);
create or replace function place_order(p_shop_id uuid,p_name text,p_phone text,p_address text,p_note text,p_items jsonb,p_total numeric) returns uuid language sql security definer as $$ insert into orders(shop_id,customer_name,phone,address,note,items,total) select id,p_name,p_phone,p_address,p_note,p_items,p_total from shops where id=p_shop_id and status<>'suspended' returning id $$;
grant execute on function place_order(uuid,text,text,text,text,jsonb,numeric) to anon,authenticated;
